### ISSUE TITLE
Renaming does not clear old name from mutual friends' lists

### ISSUE THREAD

**Issue by LlmDl** [xf57212/TownyNameUpdater#1]
Player A changes their name, Player B had Player A in their friends list.

Upon using the manual command or TownyNameUpdater to execute a name change, upon next plugin startup towny enters safe mode as Player B's residentname.txt file still contains the old Player A name (which isn't found in the residents.txt.)

Also, Hello!

**Comment by thu2468** [comment]
Wouldnt this be a towny issue not this plugin because all this plugin is doing is running /ta resident {oldname} rename {newname}

**Comment by LlmDl** [comment]
This was fixed in towny as of 0.89.2.7, I made this ticket to get the attention of the xf57212 as github doesn't have a PM function.

**Comment by thu2468** [comment]
Oh ic mb

**Comment by thu2468** [comment]
do you know where the compile version of this plugin is?

**Comment by xf57212** [comment]
https://www.dropbox.com/s/0bwjs20icu6rc84/TownyNameUpdater.jar?dl=0

**Comment by thu2468** [comment]
ty

**Comment by xf57212** [comment]
keep in mind that this plugin will only work with 1.7 and 1.8 servers since it stores a list of UUIDs and UUIDs don't exist back in 1.6
